### ISSUE TITLE
Does this thing work?

### ISSUE THREAD

**Issue by serundeputy** [backdrop-contrib/potx#1]
@olafgrabienski 
I've ported this to Backdrop, but don't know how to tell if the resulting files are correct or useful.

The only thing I've tried is:

```php
drush potx
```

which results in a 1.2M file named `general.pot` ... Is that useful? Is that what you expect?

If not maybe you can file issues against this repo until we get it into a state that is useful.

thanks!

**Comment by olafgrabienski** [comment]
**First impression:** At the moment I couln't test the module using Drush so I had a look at the UI of the module in a Backdrop installation. On `admin/config/regional/translate/extract` there are options to extract from `core/modules`, `core/themes` and `modules`. Looks like you can't extract from the whole core directory but I guess you can do this with Drush using the option `--folder` (see README of the module).

**Comment by olafgrabienski** [comment]
We tried to get the correct files using Drush:

- `drush potx single --folder=core`
- `drush potx single --folder=profiles`

Core:

- https://files.gitter.im/backdrop/backdrop-issues/fL0E/general.pot
- https://files.gitter.im/backdrop/backdrop-issues/dVeL/installer.pot

Profiles:

- https://files.gitter.im/backdrop/backdrop-issues/NtBr/general.pot

**To do:**

- check if these are really the files we need (@quicksketch?)
- if yes, build the files from ~~release 1.6.3~~ the current release
- merge the files into one
- import it into the language server

**Comment by olafgrabienski** [comment]
> check if these are really the files we need

Related: #3 (Some or all JS files are not respected by potx)

**Comment by quicksketch** [comment]
I'm going to go ahead and close this because, yes, it does work. :smile: 

Let's make new issues for individual problems. It looks like it's generating the necessary .pot files, matching what is output by the Drupal version of this module.
