### ISSUE TITLE
type int, string given error with PHP8.1

### ISSUE THREAD

**Issue by robertgarrigos** [backdrop-contrib/potx#13]
Running cron on php8.1 potx triggers an error:

```
TypeError: substr(): Argument #2 ($offset) must be of type int, string given a substr() (línia 160 de /home/modules/potx/potx.inc).
```
Changing back to php7.4 returns cron to normal functionality.

**Comment by argiepiano** [comment]
This is a syntax error created by `l10n_server`. See https://github.com/backdrop-contrib/l10n_server/issues/26

Even though this seems to "work" in 7.4, the 2nd parameter being sent to `_potx_process_file()` is still wrong (the only difference is that it doesn't throw a fatal error in 7.4).

**Comment by argiepiano** [comment]
I have provided a [PR](https://github.com/backdrop-contrib/l10n_server/pull/28) for that l10n_server issue. If you could test, that'd be great.

**Comment by robertgarrigos** [comment]
Thanks, @argiepiano This pr fixes the problem for me.

**Comment by argiepiano** [comment]
Great! Since the issue was with l10n_server, this can be closed. I don't have closing privileges in this module, hmmm...

**Comment by olafgrabienski** [comment]
> I don't have closing privileges in this module

_I_ have, closing ...
