### ISSUE TITLE
Unknown column 't.langcode' when extracting a template file

### ISSUE THREAD

**Issue by robertgarrigos** [backdrop-contrib/potx#14]
Trying to extract some pot files and get this error, which is easy to fix. this is the line 417 in potx.inc:

```
  $language_column = 'langcode';
```

but fixing this I get another one, just because I selected to download a template for a selected language, not an independent language template:

```
Unknown column 'language' in 'field list': SELECT language, name, plurals, formula FROM {language} 
```

this is more complex, because language table columns are langcode, name, direction, enabled and weight. There is not plurals nor formula column. These are the drupal columns still here.

**Comment by Egmund** [comment]
Same error here:
`SQLSTATE[42S22]: Column not found: 1054 Unknown column 't.langcode' in 'where clause': SELECT t.translation FROM {locales_source} s LEFT JOIN {locales_target} t ON t.lid = s.lid WHERE s.source = :source AND t.langcode = :langcode; Array ( [:source] => Basic settings [:langcode] => da ) `

**Comment by argiepiano** [comment]
It looks like the maintainer is not active. Pinging @serundeputy to see if they are still interested in maintaining this module and taking care of bugs?

**Comment by argiepiano** [comment]
@robertgarrigos do you remember your exact settings or do you have steps to reproduce? I'm trying to reproduce this error without success.

**Comment by argiepiano** [comment]
I was able to reproduce 🎉  

It looks like this happens when you try to extract the pot file for a specific language. If you select the "Language independent template", the export works.

**Comment by argiepiano** [comment]
OK, so, in Drupal, the table `languages` stored language information. This is done in config in Backdrop, in the file `language.settings.json`. As you can see, the json file has the many of the same keys as the columns in table `languages` in D7. 

D7:
<img width="488" alt="Screen Shot 2024-11-23 at 8 06 49 AM" src="https://github.com/user-attachments/assets/32a205dd-3a26-4238-8369-4642b2038d55">

Backdrop:
```json
{
    "_config_name": "language.settings",
    "_config_static": true,
    "language_negotiation": {
        "language": [
            "locale-url",
            "language-default"
        ]
    },
    "languages": {
        "en": {
            "langcode": "en",
            "name": "English",
            "direction": 0,
            "enabled": true,
            "weight": 0,
            "native": "English"
        },
        "es": {
            "langcode": "es",
            "name": "Spanish",
            "direction": 0,
            "native": "Español",
            "enabled": true,
            "weight": 0
        }
    }
}
```
(some original columns are missing, so they must be stored in a different way in Backdrop)

So, the code in `potx.inc` has to be adapted to read from json, rather than doing a db query. I'll try a PR.

**Comment by argiepiano** [comment]
@robertgarrigos, @egmund, I have provided a PR. Can you please test? This should allow you to export a template for a specific language, with translations, which created many errors before.
<img width="782" alt="Screen Shot 2024-11-23 at 8 57 17 AM" src="https://github.com/user-attachments/assets/efc42972-83e6-4929-a880-be02dafaca9c">



The problem stemmed from the fact that Backdrop stores language-related stuff in a different way. To begin with, the language information (name, direction, etc) is stored as json files. The plurals and formulas are stored as a state in the `state` table.

I think I caught all of them, but may be not. If you find issues, please post here.

**Comment by argiepiano** [comment]
@Egmund I got notified about a comment you posted about not finding the diff file - it seems like that was deleted.

To get the diff file visit:
https://github.com/backdrop-contrib/potx/pull/15.diff

This is standard in github (notice I added `.diff` at the end)

**Comment by argiepiano** [comment]
BTW, please apply the diff to the dev version (not the latest release).

**Comment by Egmund** [comment]
I get an error after 'fixing the .inc file:
`syntax error, unexpected token "@", expecting "]" `

**Comment by argiepiano** [comment]
@Egmund please post the line number where this happened.

**Comment by argiepiano** [comment]
> syntax error, unexpected token "@", expecting "]" 

This may have been the result of how you patched the file. How did you do that? Manually? Or did you use `patch -p1 <15.diff` after switching to the `potx` folder?

**Comment by robertgarrigos** [comment]
I am not getting @Egmund's error. Although I'm having some of these:

```
The first parameter to t() should be a literal string. There should be no variables, concatenation, constants or other non-literal strings there. At t($message,$replace) in backup_migrate.module on line 1747. Read more at http://drupal.org/node/322732
The first two watchdog() parameters should be literal strings. There should be no variables, concatenation, constants or even a t() call there. At watchdog('backup_migrate',$message,$replace,$type=='error'?WATCHDOG_ERROR:WATCHDOG_NOTICE) in backup_migrate.module on line 1756. Read more at http://drupal.org/node/323101
In format_plural(), the singular and plural strings should be literal strings. There should be no variables, concatenation, constants or even a t() call there. At format_plural(($this->period/$period['seconds']),$period['singular'],$period['plural']) in includes/schedules.inc on line 312. Read more at http://drupal.org/node/323072
```

which I guess they are problems within the contrib module I was extracting from, not with potx module.

**Comment by robertgarrigos** [comment]
> > syntax error, unexpected token "@", expecting "]"
> 
> This may have been the result of how you patched the file. How did you do that? Manually? Or did you use `patch -p1 <15.diff` after switching to the `potx` folder?

I find very useful to use Github CLI to download the pr. For this case it would be `gh pr checkout 15`

**Comment by argiepiano** [comment]
Thanks for testing!

> which I guess they are problems within the contrib module I was extracting from, not with potx module.

Yes, this is a common problem with some modules (using variables and concatenation within `t()`). `potx` just detects those and warns you. The `po` file is still usable.

Thanks for the tip on using Github CLI to test PRs!

**Comment by Egmund** [comment]
Sorry for the delay in responding.
Yes, I did manually patch the original potx file on my site.
I think I will just await an official update to potx. I do not really need this module right now.

**Comment by argiepiano** [comment]
Thanks @Egmund. 

Since it looks like the maintainer is not active in the community, I'm pinging the @backdrop-contrib/bug-squad to keep this PR in the radar, for merging and doing a new release, given that this produces fatal errors. At least one person besides me has tested and confirmed this works.

**Comment by herbdool** [comment]
Ok, please post a reminder in a couple weeks if the maintainer doesn't respond. Will merge then.

**Comment by Egmund** [comment]
Here is offending line from log:
`ParseError: syntax error, unexpected token "@", expecting "]" i module_load_include() (linje 450 af /home/haurdaln/butik2.havredalzendo.dk/modules/potx/potx.inc).`

```
     else {
        // More plural versions only if required, with the lookup source
        // string modified as imported into the database.
        **$strings[] = str_replace('@count', '@count['. $plural_index .']', $plural);**
      }
      $plural_index++;
    }

```

**Comment by argiepiano** [comment]
Great, thanks for checking.  I think this is a problem for languages where there are more than one plural form, which I don't have.

EDIT: can you let me know for which language this is happening? And can you share the plural setting and formula for it?

**Comment by argiepiano** [comment]
OK, so, here's another issue. The line that you highlighted is 451, not 450. So, there is a chance that during your manual patching you missed something. Can you please test by not doing a manual patching, but rather applying the patch with the method I posted above?

**Comment by Egmund** [comment]
I did the patch your way - much easier - and the module now works as intended it seems.
Thank you for taking time with this.

**Comment by argiepiano** [comment]
Great! Thanks!
